import type { ComponentProps, ReactNode } from 'react';
import { Text, View, useWindowDimensions } from 'react-native';
import type { DashboardView } from '../dashboard/dashboard';
import { Card } from '../ui/components/Card';
import { MetricCard } from '../ui/components/MetricCard';
import { SectionHeader } from '../ui/components/SectionHeader';
import { colors, spacing, typography } from '../ui/tokens';
import { CaptureScreen } from './CaptureScreen';

type Copy = { readonly kicker: string; readonly subtitle: string; readonly note: string; readonly capture: string; readonly processing: string; readonly unavailable: string; readonly device: string; readonly hint: string; readonly placeholder: string; readonly extract: string; readonly unavailableHint: string; readonly saved: string; readonly installed: string; readonly explore: string; readonly clients: string; readonly sites: string; readonly units: string; readonly records: string; readonly modality: string; readonly brand: string; readonly model: string };
type Summary = { readonly clients: number; readonly sites: number; readonly rows: number; readonly units: number };

export function OverviewScreen({ copy, summary, view = { status: 'empty', clients: [], aggregation: null }, captureProps, extraction }: { readonly copy: Copy; readonly summary: Summary; readonly view?: DashboardView; readonly captureProps: ComponentProps<typeof CaptureScreen>; readonly extraction: ReactNode }) {
  const compact = useWindowDimensions().width < 840;
  const equipment = view.clients.flatMap(client => client.sites.flatMap(site => site.equipment));
  const modalityCounts = [...equipment.reduce((counts, item) => counts.set(item.modality, (counts.get(item.modality) ?? 0) + item.quantity), new Map<string, number>())].sort((a, b) => b[1] - a[1]);
  return <View>
    <View style={{ marginBottom: spacing.xxl }}><Text style={{ color: colors.primary, fontSize: typography.sizes.xs, fontWeight: typography.weights.bold, letterSpacing: 1.2, marginBottom: spacing.sm }}>{copy.kicker}</Text><Text style={{ color: colors.text, fontSize: 32, lineHeight: 38, fontWeight: typography.weights.bold }}>FieldSight</Text><Text style={{ color: colors.text, fontSize: typography.sizes.xl, marginTop: spacing.sm }}>Inteligencia de campo para equipos médicos</Text><Text style={{ color: colors.textSecondary, fontSize: typography.sizes.md, marginTop: spacing.xs }}>Convierte observaciones del terreno en información confiable. Con IA local.</Text></View>
    <View style={{ flexDirection: compact ? 'column' : 'row', gap: spacing.md, marginBottom: spacing.xxl }}>{[[copy.clients, summary.clients, colors.primary], [copy.sites, summary.sites, colors.primary], ['Equipos instalados', summary.units, colors.success]].map(([label, value, accent]) => <MetricCard key={String(label)} label={String(label)} value={value as number} accent={String(accent)} style={{ flex: 1, minWidth: compact ? undefined : 0 }} />)}</View>
    <View style={{ flexDirection: compact ? 'column' : 'row', gap: spacing.lg, marginBottom: spacing.xxl }}><Card style={{ flex: 1 }}><SectionHeader title="Equipos por modalidad" subtitle="Unidades instaladas en la vista actual" />{modalityCounts.length === 0 ? <Text style={{ color: colors.textSecondary }}>Sin datos disponibles</Text> : modalityCounts.map(([modality, count]) => <View key={modality} style={{ flexDirection: 'row', alignItems: 'center', marginBottom: spacing.md }}><View style={{ width: 9, height: 9, borderRadius: 5, backgroundColor: colors.primary, marginRight: spacing.md }} /><Text style={{ flex: 1, color: colors.text, fontSize: typography.sizes.md }}>{modality}</Text><Text style={{ color: colors.text, fontWeight: typography.weights.semibold }}>{count}</Text></View>)}</Card><Card style={{ flex: 1 }}><SectionHeader title="Base instalada por cliente" subtitle="Clientes y sedes con equipos registrados" />{view.clients.length === 0 ? <Text style={{ color: colors.textSecondary }}>Sin datos disponibles</Text> : view.clients.map(client => <View key={client.clientName} style={{ flexDirection: 'row', alignItems: 'center', paddingVertical: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.border }}><View style={{ flex: 1 }}><Text style={{ color: colors.text, fontSize: typography.sizes.md, fontWeight: typography.weights.semibold }}>{client.clientName}</Text><Text style={{ color: colors.textSecondary, fontSize: typography.sizes.xs, marginTop: spacing.xs }}>{client.sites.length} {copy.sites}</Text></View><Text style={{ color: colors.text, fontWeight: typography.weights.bold }}>{client.quantity}</Text></View>)}</Card></View>
    <Card style={{ marginBottom: spacing.xxl }}><SectionHeader title="Observaciones recientes" subtitle="Últimas observaciones disponibles en el dispositivo" />{extraction ?? <Text style={{ color: colors.textSecondary }}>Las observaciones recientes aparecerán después de guardar una Field note.</Text>}</Card>
    <CaptureScreen {...captureProps} />
  </View>;
}
