import { useEffect, useMemo, useRef, useState } from 'react';
import { Animated, ScrollView, Text, View } from 'react-native';
import { captureObservation } from './capture/observation-capture';
import { QVACObservationExtractor } from './capture/qvac-extractor';
import { loadQvacModel, unloadQvacModel } from './capture/qvac-runtime';
import { dashboardView, type DashboardView } from './dashboard/dashboard';
import type { Modality } from './domain/modality';
import type { Observation } from './domain/observation';
import { loadSyntheticFixtures } from './fixtures/seed';
import { AppShell } from './layout/AppShell';
import type { AppSection } from './layout/DesktopSidebar';
import { CaptureScreen } from './screens/CaptureScreen';
import { InstalledBaseScreen } from './screens/InstalledBaseScreen';
import { OverviewScreen } from './screens/OverviewScreen';
import { InstalledBase } from './store/installed-base';
import { MemoryObservationStore } from './store/memory-observation-store';

type DemoState = 'loading' | 'ready' | 'offline' | 'empty' | 'no-results';
type Language = 'en' | 'es';
const MODALITIES: readonly (Modality | null)[] = [null, 'MRI', 'CT', 'Ultrasound'];
const COPY = { en: { kicker: 'FIELD INTELLIGENCE', subtitle: 'Capture field notes and reconcile the installed base by client, site, and equipment.', note: 'FIELD NOTE', capture: 'Observation capture', processing: 'Processing', unavailable: 'Model unavailable', device: 'On-device', hint: 'Describe the visit in natural language. The local extractor turns it into structured equipment records.', placeholder: 'Two MRI machines at Pacific Hospital, client DemoCare, brand NovaMed, model N-1', extract: 'Extract observation', unavailableHint: 'Capture is unavailable while local data is loading or offline.', saved: 'Observation saved', installed: 'INSTALLED BASE', explore: 'EXPLORE', clients: 'clients', sites: 'sites', units: 'units', records: 'records', modality: 'Modality', brand: 'Brand', model: 'Model' }, es: { kicker: 'INTELIGENCIA DE CAMPO', subtitle: 'Captura notas de campo y reconcilia la base instalada por cliente, sede y equipo.', note: 'NOTA DE CAMPO', capture: 'Captura de observación', processing: 'Procesando', unavailable: 'Modelo no disponible', device: 'En dispositivo', hint: 'Describe la visita en lenguaje natural. El extractor local la convierte en registros estructurados de equipos.', placeholder: 'Dos equipos de MRI en Pacific Hospital, cliente DemoCare, marca NovaMed, modelo N-1', extract: 'Extraer observación', unavailableHint: 'La captura no está disponible mientras se cargan los datos locales o estás sin conexión.', saved: 'Observación guardada', installed: 'BASE INSTALADA', explore: 'EXPLORAR', clients: 'clientes', sites: 'sedes', units: 'unidades', records: 'registros', modality: 'Modalidad', brand: 'Marca', model: 'Modelo' } } as const;
function summary(view: DashboardView) { const sites = new Set<string>(); let rows = 0; for (const client of view.clients) for (const site of client.sites) { sites.add(`${client.clientName}/${site.siteName}`); rows += site.equipment.length; } return { clients: view.clients.length, sites: sites.size, rows, units: view.aggregation?.quantity ?? 0 }; }
function statusFor(status: DashboardView['status']) { return { loading: ['Loading', 'Reading the installed base…'], offline: ['Offline', 'Field data is unavailable. Try again when connected.'], empty: ['No installed base yet', 'Capture your first Observation to get started.'], 'no-results': ['No matching equipment', 'Nothing is installed for the selected filter.'], ready: ['Installed base', 'Reported equipment per Client and Site.'] }[status] as [string, string]; }

export default function App() {
  const [base, setBase] = useState<InstalledBase | null>(null); const [store, setStore] = useState<MemoryObservationStore | null>(null); const [qvacModelId, setQvacModelId] = useState<string | null>(null); const [fieldNote, setFieldNote] = useState(''); const [captureState, setCaptureState] = useState<'empty' | 'loading' | 'error' | 'saved'>('empty'); const [captureError, setCaptureError] = useState(''); const [captured, setCaptured] = useState<readonly Observation[]>([]); const [demo, setDemo] = useState<DemoState>('loading'); const [selectedModality, setSelectedModality] = useState<Modality | null>(null); const [selectedBrand, setSelectedBrand] = useState<string | null>(null); const [selectedModel, setSelectedModel] = useState<string | null>(null); const [language] = useState<Language>('en'); const [activeSection, setActiveSection] = useState<AppSection>('overview'); const opacity = useRef(new Animated.Value(0)).current; const offset = useRef(new Animated.Value(10)).current; const scrollRef = useRef<ScrollView>(null); const captureOffset = useRef(0); const inventoryOffset = useRef(0);
  useEffect(() => { let active = true; const timer = setTimeout(() => { const nextStore = new MemoryObservationStore(); void loadSyntheticFixtures(nextStore).then(observations => { if (!active) return; const nextBase = new InstalledBase(); observations.forEach(observation => nextBase.update(observation)); setBase(nextBase); setStore(nextStore); setDemo('ready'); }).catch(() => { if (active) setDemo('offline'); }); }, 500); return () => { active = false; clearTimeout(timer); }; }, []);
  useEffect(() => { Animated.parallel([Animated.timing(opacity, { toValue: 1, duration: 420, useNativeDriver: true }), Animated.spring(offset, { toValue: 0, tension: 60, friction: 9, useNativeDriver: true })]).start(); }, [offset, opacity]);
  useEffect(() => { let active = true; void loadQvacModel().then(id => { if (active) setQvacModelId(id); else void unloadQvacModel(id); }).catch(() => { if (active) { setCaptureError('QVAC could not load its on-device model.'); setCaptureState('error'); } }); return () => { active = false; }; }, []);
  const view = useMemo(() => { const source = base ?? new InstalledBase(); if (demo === 'loading') return dashboardView(source, {}, { loading: true }); if (demo === 'offline') return dashboardView(source, {}, { offline: true }); if (demo === 'empty') return dashboardView(new InstalledBase()); if (demo === 'no-results') return dashboardView(source, { modality: 'CT', brand: 'not-installed' }); return dashboardView(source, { ...(selectedModality === null ? {} : { modality: selectedModality }), ...(selectedBrand === null ? {} : { brand: selectedBrand }), ...(selectedModel === null ? {} : { model: selectedModel }) }); }, [base, demo, selectedBrand, selectedModel, selectedModality]);
  const copy = COPY[language]; const totals = summary(view); const [statusTitle, statusDetail] = statusFor(view.status); const brandOptions = useMemo(() => [...new Set((base?.all() ?? []).flatMap(record => record.brand === null ? [] : [record.brand]))].sort(), [base]); const modelOptions = useMemo(() => [...new Set((base?.all() ?? []).flatMap(record => record.model === null ? [] : [record.model]))].sort(), [base]);
  async function saveFieldNote() { if (store === null) return; setCaptureState('loading'); setCaptureError(''); try { if (qvacModelId === null) throw new Error('QVAC is still loading its on-device model.'); const observations = await captureObservation(fieldNote, new QVACObservationExtractor(qvacModelId), store); const next = new InstalledBase(); (await store.all()).forEach(item => next.update(item)); setBase(next); setCaptured(observations); setCaptureState('saved'); setFieldNote(''); } catch (error) { setCaptureError(error instanceof Error ? error.message : 'Could not extract this Field note.'); setCaptureState('error'); } }
  function navigate(section: AppSection) { setActiveSection(section); scrollRef.current?.scrollTo({ y: Math.max(0, section === 'capture' ? captureOffset.current : section === 'inventory' ? inventoryOffset.current : 0) - 18, animated: true }); }
  const captureProps = { copy, fieldNote, setFieldNote: (value: string) => { setFieldNote(value); if (captureState !== 'empty') setCaptureState('empty'); }, captureState, captureDisabled: store === null || qvacModelId === null || fieldNote.trim() === '', captureError, onSave: () => void saveFieldNote(), onLayout: (event: { nativeEvent: { layout: { y: number } } }) => { captureOffset.current = event.nativeEvent.layout.y; } };
  const extraction = captured.length === 0 ? null : <View style={{ backgroundColor: '#fff', padding: 16, marginBottom: 16, borderRadius: 8 }}><Text style={{ fontWeight: '800' }}>{copy.saved}</Text>{captured.map(observation => <View key={observation.id} style={{ marginTop: 8 }}><Text>{observation.site.client.name} / {observation.site.name}</Text><Text>{observation.quantity} x {observation.modality} · {observation.brand ?? 'Unknown brand'} · {observation.model ?? 'Unknown model'}</Text></View>)}</View>;
  return <AppShell activeSection={activeSection} onNavigate={navigate} scrollRef={scrollRef} opacity={opacity} offset={offset}><OverviewScreen copy={copy} summary={totals} captureProps={captureProps} extraction={extraction} /><InstalledBaseScreen view={view} status={{ title: statusTitle, detail: statusDetail }} copy={copy} demo={demo} modalities={MODALITIES} selectedModality={selectedModality} onModality={value => setSelectedModality(value as Modality | null)} brandOptions={brandOptions} selectedBrand={selectedBrand} onBrand={setSelectedBrand} modelOptions={modelOptions} selectedModel={selectedModel} onModel={setSelectedModel} onClear={() => { setSelectedModality(null); setSelectedBrand(null); setSelectedModel(null); }} /></AppShell>;
}
