import { Moon, Sun } from 'lucide-react-native';
import { useState } from 'react';
import { Pressable, Text, View } from 'react-native';
import { spacing, typography, useTheme } from '../ui/tokens';

export function DesktopTopbar({ language, onLanguage }: { readonly language: 'en' | 'es' | 'pt'; readonly onLanguage: (language: 'en' | 'es' | 'pt') => void }) {
  const { colors, resolvedMode, setMode } = useTheme();
  const [languageOpen, setLanguageOpen] = useState(false);
  return <View style={{ height: 74, zIndex: 20, backgroundColor: colors.surface, borderBottomWidth: 1, borderBottomColor: colors.border, paddingHorizontal: spacing.xxl, flexDirection: 'row', alignItems: 'center', gap: spacing.lg }}><View style={{ flex: 1 }} /><View style={{ position: 'relative', zIndex: 30 }}><Pressable accessibilityRole="button" accessibilityLabel="Change language" onPress={() => setLanguageOpen(!languageOpen)}><Text style={{ color: colors.primary, fontSize: typography.sizes.xs, fontWeight: typography.weights.bold }}>{language.toUpperCase()} ▾</Text></Pressable>{languageOpen && <View style={{ position: 'absolute', top: 28, right: 0, zIndex: 40, minWidth: 88, backgroundColor: colors.surface, borderColor: colors.borderStrong, borderWidth: 1, borderRadius: 10, padding: 4, boxShadow: `0px 5px 12px ${colors.text}2E` }}>{(['en', 'es', 'pt'] as const).map(item => <Pressable key={item} onPress={() => { onLanguage(item); setLanguageOpen(false); }} style={{ paddingHorizontal: 12, paddingVertical: 10, borderRadius: 7, backgroundColor: item === language ? colors.primarySoft : 'transparent' }}><Text style={{ color: item === language ? colors.primary : colors.text, fontWeight: item === language ? typography.weights.bold : typography.weights.medium }}>{item.toUpperCase()}</Text></Pressable>)}</View>}</View><Pressable accessibilityRole="button" accessibilityLabel="Toggle theme" onPress={() => setMode(resolvedMode === 'dark' ? 'light' : 'dark')}><View style={{ width: 32, height: 32, borderRadius: 16, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' }}>{resolvedMode === 'dark' ? <Sun size={16} color={colors.primary} /> : <Moon size={16} color={colors.primary} />}</View></Pressable><View><Text style={{ color: colors.text, fontSize: typography.sizes.sm, fontWeight: typography.weights.semibold }}>Collaborator</Text><Text style={{ color: colors.textSecondary, fontSize: typography.sizes.xs }}>Field team</Text></View></View>;
}
