import { Text, TouchableOpacity, View } from 'react-native';
import { colors, radius, spacing, typography } from '../ui/tokens';

export type AppSection = 'overview' | 'capture' | 'inventory';

export function DesktopSidebar({ activeSection, onNavigate }: { readonly activeSection: AppSection; readonly onNavigate: (section: AppSection) => void }) {
  const items: readonly [AppSection, string, string][] = [['overview', '⌂', 'Resumen'], ['capture', '+', 'Captura'], ['inventory', '▦', 'Base instalada']];
  return <View style={{ width: 216, backgroundColor: colors.surface, borderRightWidth: 1, borderRightColor: colors.border, paddingHorizontal: spacing.lg, paddingTop: spacing.xl, paddingBottom: spacing.lg, justifyContent: 'space-between' }}><View><View style={{ flexDirection: 'row', alignItems: 'center', gap: spacing.sm, marginBottom: spacing.xxxl }}><View style={{ width: 36, height: 36, borderRadius: radius.md, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' }}><Text style={{ color: colors.white, fontSize: 20, fontWeight: typography.weights.bold }}>F</Text></View><Text style={{ color: colors.text, fontSize: typography.sizes.md, fontWeight: typography.weights.bold }}>FieldSight</Text></View>{items.map(([section, icon, label]) => <TouchableOpacity key={section} accessibilityRole="button" accessibilityLabel={label} onPress={() => onNavigate(section)} style={{ minHeight: 42, flexDirection: 'row', alignItems: 'center', gap: spacing.md, paddingHorizontal: spacing.md, marginBottom: spacing.xs, borderRadius: radius.sm, backgroundColor: activeSection === section ? colors.primarySoft : 'transparent', borderLeftWidth: activeSection === section ? 3 : 0, borderLeftColor: colors.primary }}><Text style={{ width: 18, color: activeSection === section ? colors.primary : colors.textSecondary, textAlign: 'center', fontSize: typography.sizes.lg }}>{icon}</Text><Text style={{ color: activeSection === section ? colors.primary : colors.textSecondary, fontSize: typography.sizes.sm, fontWeight: activeSection === section ? typography.weights.semibold : typography.weights.medium }}>{label}</Text></TouchableOpacity>)}<TouchableOpacity style={{ minHeight: 42, flexDirection: 'row', alignItems: 'center', gap: spacing.md, paddingHorizontal: spacing.md }}><Text style={{ width: 18, color: colors.textSecondary, textAlign: 'center' }}>⚙</Text><Text style={{ color: colors.textSecondary, fontSize: typography.sizes.sm }}>Configuración</Text></TouchableOpacity></View><View style={{ borderTopWidth: 1, borderTopColor: colors.border, paddingTop: spacing.lg, flexDirection: 'row', alignItems: 'center', gap: spacing.sm }}><View style={{ width: 30, height: 30, borderRadius: 15, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' }}><Text style={{ color: colors.primary, fontWeight: typography.weights.bold }}>Q</Text></View><Text style={{ color: colors.textSecondary, fontSize: typography.sizes.xs }}>Local workspace</Text></View></View>;
}
